# Generated by Django 3.2.3 on 2021-06-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_materia_data_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='texto_post',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
