# Generated by Django 3.2.3 on 2021-06-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_materia_texto_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='descricao',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materia',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
