# Generated by Django 3.2.3 on 2021-06-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210602_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacionada',
            old_name='materia_relacionada',
            new_name='proxima_materia',
        ),
        migrations.RemoveField(
            model_name='relacionada',
            name='observacao',
        ),
    ]
