# Generated by Django 3.2.3 on 2021-06-07 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20210603_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionada',
            name='anterior_materia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relacionada',
            name='materia_relacionado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.materia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relacionada',
            name='proxima_materia',
            field=models.IntegerField(),
        ),
    ]
