# Generated by Django 3.2.3 on 2021-06-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210607_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacionada',
            name='anterior_materia',
        ),
        migrations.RemoveField(
            model_name='relacionada',
            name='materia_relacionado',
        ),
        migrations.AlterField(
            model_name='relacionada',
            name='proxima_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.materia'),
        ),
        migrations.CreateModel(
            name='Proxima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Anterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.materia')),
            ],
        ),
    ]
