# Generated by Django 3.2.3 on 2021-06-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20210607_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anterior',
            old_name='relacionado',
            new_name='anterior',
        ),
        migrations.RenameField(
            model_name='proxima',
            old_name='relacionado',
            new_name='anterior',
        ),
    ]
