# Generated by Django 3.2.3 on 2021-06-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20210607_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxima',
            old_name='anterior',
            new_name='proximo',
        ),
    ]
