# Generated by Django 3.2.3 on 2021-06-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_rename_anterior_proxima_proximo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anterior',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proxima',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
